// utils/roles.js

module.exports = [ { id: 'villager', name: 'Villager', description: 'An ordinary villager. Survive and find the werewolves.', alignment: 'Village', powerName: null, buttonLabel: null, icon: 'https://cdn-icons-png.flaticon.com/512/616/616408.png', logic: async ({ userId, guildId, targetId, db, interaction }) => { return interaction.reply({ content: 'Villagers have no special power.', ephemeral: true }); } }, { id: 'werewolf', name: 'Werewolf', description: 'Hunt the villagers by killing one each night.', alignment: 'Werewolf', powerName: 'Kill', buttonLabel: 'Bite Target', icon: 'https://cdn-icons-png.flaticon.com/512/616/616491.png', logic: async ({ userId, guildId, targetId, db, interaction }) => { if (!targetId) return interaction.reply({ content: 'Please specify a target.', ephemeral: true }); // Log attack (would resolve at night) await db.collection('games').doc(guildId).collection('nightActions').doc(userId).set({ action: 'kill', targetId }); return interaction.reply({ content: You have marked <@${targetId}> for elimination., ephemeral: true }); } }, { id: 'seer', name: 'Seer', description: 'Each night, you may peek at one player's true role.', alignment: 'Village', powerName: 'Reveal Role', buttonLabel: 'Divine', icon: 'https://cdn-icons-png.flaticon.com/512/3534/3534103.png', logic: async ({ userId, guildId, targetId, db, interaction }) => { if (!targetId) return interaction.reply({ content: 'Please specify a target to divine.', ephemeral: true }); const playerRef = db.collection('games').doc(guildId).collection('players').doc(targetId); const playerSnap = await playerRef.get(); if (!playerSnap.exists) return interaction.reply({ content: 'That player is not in the game.', ephemeral: true });

const role = playerSnap.data().role?.name || 'Unknown';
  return interaction.reply({ content: `<@${targetId}> is a **${role}**.`, ephemeral: true });
}

}, { id: 'guard', name: 'Bodyguard', description: 'Protect one player each night from being killed.', alignment: 'Village', powerName: 'Protect', buttonLabel: 'Shield', icon: 'https://cdn-icons-png.flaticon.com/512/3523/3523885.png', logic: async ({ userId, guildId, targetId, db, interaction }) => { if (!targetId) return interaction.reply({ content: 'Please specify someone to guard.', ephemeral: true }); await db.collection('games').doc(guildId).collection('nightActions').doc(userId).set({ action: 'protect', targetId }); return interaction.reply({ content: You will protect <@${targetId}> tonight., ephemeral: true }); } }, { id: 'hunter', name: 'Hunter', description: 'If you are killed, you may shoot another player.', alignment: 'Village', powerName: null, buttonLabel: null, icon: 'https://cdn-icons-png.flaticon.com/512/3468/3468857.png', logic: async () => {} // Triggered only on death, separate logic }, { id: 'cupid', name: 'Cupid', description: 'Link two players as lovers. If one dies, the other dies of heartbreak.', alignment: 'Neutral', powerName: 'Link Lovers', buttonLabel: 'Link', icon: 'https://cdn-icons-png.flaticon.com/512/2588/2588445.png', logic: async ({ userId, guildId, targetId, db, interaction }) => { if (!targetId) return interaction.reply({ content: 'Choose two players to link as lovers.', ephemeral: true }); const targets = targetId.split(','); if (targets.length !== 2) return interaction.reply({ content: 'Exactly two targets required.', ephemeral: true });

await db.collection('games').doc(guildId).collection('loverLinks').doc(userId).set({ lovers: targets });
  return interaction.reply({ content: `You have linked <@${targets[0]}> and <@${targets[1]}> as lovers.`, ephemeral: true });
}

} ];


